from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field
from datetime import datetime
from enum import Enum
import uuid

# --- Enums ---
class AssetClass(str, Enum):
    CRYPTO = "CRYPTO"
    EQUITIES = "EQUITIES"
    FOREX = "FOREX"
    COMMODITIES = "COMMODITIES"

class StrategyType(str, Enum):
    MEAN_REVERSION = "MEAN_REVERSION"
    MOMENTUM = "MOMENTUM"
    ARBITRAGE = "ARBITRAGE"
    ML_PREDICTIVE = "ML_PREDICTIVE"

class RegimeType(str, Enum):
    BULL_TREND = "BULL_TREND"
    BEAR_TREND = "BEAR_TREND"
    RANGE_BOUND = "RANGE_BOUND"
    HIGH_VOLATILITY = "HIGH_VOLATILITY"
    LIQUIDITY_CRISIS = "LIQUIDITY_CRISIS"

# --- Domain Models ---

class StrategySpec(BaseModel):
    """Defines a generated trading strategy."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str
    description: str
    strategy_type: StrategyType
    asset_class: AssetClass
    target_symbols: List[str]
    parameters: Dict[str, Any]
    created_at: datetime = Field(default_factory=datetime.utcnow)
    version: int = 1
    
    # Performance Metrics (from Backtest)
    sharpe_ratio: Optional[float] = None
    max_drawdown: Optional[float] = None
    win_rate: Optional[float] = None
    robustness_score: Optional[float] = None # 0.0 to 1.0

class MarketRegime(BaseModel):
    """Current market state detected by Regime Agent."""
    asset_class: AssetClass
    regime: RegimeType
    confidence: float
    detected_at: datetime
    metadata: Dict[str, Any] # e.g. vol drivers, macro factors

class Signal(BaseModel):
    """Raw signal generated by a Strategy."""
    strategy_id: str
    symbol: str
    timestamp: datetime
    signal_strength: float # -1.0 (Strong Sell) to 1.0 (Strong Buy)
    metadata: Dict[str, Any] = {}

class ExecutionOptions(BaseModel):
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    order_type: str = "LIMIT"
    
class ExecutionPacket(BaseModel):
    """Final output for the user/broker."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    strategy_id: str
    symbol: str
    side: str # BUY / SELL
    quantity: float
    limit_price: Optional[float] = None
    options: ExecutionOptions
    status: str = "PENDING_APPROVAL"
    rationale: str # Auto-generated explanation
